### ISSUE TITLE
Update workflows for web and API 

### ISSUE THREAD

**Issue by adizafri2000** [adizafri2000/adaTanam#23]
**Quoting ChatGPT:**

To achieve this, you can utilize the `paths` filter in your workflow triggers. The `paths` filter allows you to specify which files or directories should trigger the workflow when they are modified. You can set up separate workflows for your web and backend folders and use `paths` to ensure that changes in one folder only trigger the corresponding workflow.

Here's how you can structure your workflows:

1. Create separate workflow files for web and backend, e.g., `web-ci.yml` and `backend-ci.yml`.
2. Configure the `paths` filter in each workflow to specify the directories that should trigger the workflow.
3. Use a combination of `push` and `pull_request` events to trigger the workflows.

Here's an example of how you can set up the workflows:

**web-ci.yml**:
```yaml
name: CI/CD for Web

on:
  push:
    branches:
      - dev
    paths:
      - 'web/**' # Adjust the path to your web directory
  pull_request:
    paths:
      - 'web/**' # Adjust the path to your web directory

jobs:
  # Your build and deploy steps for the web here
```

**backend-ci.yml**:
```yaml
name: CI/CD for Backend

on:
  push:
    branches:
      - dev
    paths:
      - 'backend/**' # Adjust the path to your backend directory
  pull_request:
    paths:
      - 'backend/**' # Adjust the path to your backend directory

jobs:
  # Your build and deploy steps for the backend here
```

With this setup, changes made in the `web` directory will only trigger the `web-ci.yml` workflow, and changes made in the `backend` directory will only trigger the `backend-ci.yml` workflow. If changes are made in both directories, both workflows will be triggered independently.
